events {
  worker_connections 1024;
}

http {
  server {
      listen 80;
      server_name pipelines.venebre.com;
      return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name pipelines.venebre.com;

    # Let's Encrypt SSL certificates
    ssl_certificate     /etc/letsencrypt/live/pipelines.venebre.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pipelines.venebre.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
      proxy_pass         http://prefect-server:4200;
      proxy_http_version 1.1;

      # -------------------------------------------------------------------------
      # WEBSOCKET SUPPORT
      # Required for Prefect UI to stream real-time logs and update flow states.
      # Ref: https://nginx.org/en/docs/http/websocket.html
      # -------------------------------------------------------------------------
      proxy_set_header Upgrade    $http_upgrade;
      proxy_set_header Connection "upgrade";

      # Passes the original client's IP and protocol information to the Prefect backend
      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
