events {
    worker_connections 1024;
}

http {
    proxy_cache_path /tmp/nginx_auth_cache levels=1:2 keys_zone=auth_cache:10m max_size=50m inactive=1h;

    server {
        listen 80;
        server_name pipelines.venebre.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name pipelines.venebre.com;

        ssl_certificate /etc/letsencrypt/live/pipelines.venebre.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pipelines.venebre.com/privkey.pem;

        location /oauth2/ {
            proxy_pass http://oauth2-proxy:4180;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Auth-Request-Redirect $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /oauth2/auth {
            proxy_pass http://oauth2-proxy:4180;
            proxy_set_header Host $host;
            
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            
            proxy_cache auth_cache;
            proxy_cache_key "$http_cookie";
            proxy_cache_valid 200 202 1h;
            proxy_cache_valid 401 403 0s;
        }

        location / {
            auth_request /oauth2/auth;
            error_page 401 = @oauth2_start;

            proxy_pass http://prefect-server:4200;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        
        location @oauth2_start {
            return 302 /oauth2/start?rd=$request_uri;
        }
    }
}