name: Deploy Infrastructure to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-infra.yml'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Infra folder to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.GCP_VM_IP }}
          username: ${{ vars.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: "infra/*"
          target: "~/venebre-prefect"

      - name: Execute Deployment on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.GCP_VM_IP }}
          username: ${{ vars.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd ~/venebre-prefect

            cat > infra/.env <<'ENV'
            GITHUB_CLIENT_ID=${{ vars.OAUTH_CLIENT_ID }}
            GITHUB_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}
            OAUTH2_PROXY_COOKIE_SECRET=${{ secrets.OAUTH_COOKIE_SECRET }}
            OAUTH_GITHUB_USERS=${{ vars.OAUTH_GITHUB_USERS }}
            ENV
            chmod 600 infra/.env
            
            echo "Restarting Containers"
            docker compose -f infra/docker-compose.yml up -d --build --force-recreate 
            
            echo "Cleaning old images"
            docker image prune -f 
