name: Deploy Infrastructure to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-infra.yml'

jobs:
  deploy-control-plane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Infra folder to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: "infra/*"
          target: "~/venebre-prefect"

      - name: Execute Deployment on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd ~/venebre-prefect

            echo "GITHUB_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" > infra/.env
            echo "GITHUB_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> infra/.env
            echo "OAUTH2_PROXY_COOKIE_SECRET=${{ secrets.OAUTH_COOKIE_SECRET }}" >> infra/.env
            echo "ALLOWED_EMAILS=${{ secrets.OAUTH_ALLOWED_EMAILS }}" >> infra/.env
            chmod 600 infra/.env
            
            echo "Restarting Containers"
            docker compose -f infra/docker-compose.yml up -d --build
            
            echo "Cleaning old images"
            docker image prune -f 